version: "3.8"
volumes:
  modules_data:
  wrangler_data:
  db_data:

services:
  app:
    build: .
    image: slowhand/nodejs
    container_name: "hono-prisma-workers"
    volumes:
      - ..:/usr/src
      - modules_data:/usr/src/node_modules
      - wrangler_data:/home/vscode/.config/.wrangler
    command: /bin/sh -c "while sleep 1000; do :; done"
    working_dir: /usr/src
    ports:
      - "8787:8787"
      - "5555:5555"
  db:
    image: postgres:16.2
    container_name: postgres_pta
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
