version: "3.8"
volumes:
  modules_data:
  wrangler_data:

services:
  app:
    build: .
    image: slowhand/nodejs
    container_name: "hono-prisma-workers"
    volumes:
      - ..:/usr/src
      - modules_data:/usr/src/node_modules
      - wrangler_data:/home/vscode/.config/.wrangler
    command: /bin/sh -c "while sleep 1000; do :; done"
    working_dir: /usr/src
    ports:
      - "8787:8787"
